version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
