/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as IndexRouteImport } from './routes/index'

const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/migrate': typeof MigrateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/migrate': typeof MigrateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/migrate': typeof MigrateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/migrate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/migrate'
  id: '__root__' | '/' | '/migrate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MigrateRoute: typeof MigrateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MigrateRoute: MigrateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
